easy_admin:
  site_name: "<img style='width:100px;opacity:0.7;' src='https://icon-library.net/images/vampire-icon/vampire-icon-12.jpg' />"
  design:
    menu:
      - label: "Exodia"
        children:
          - { label: "IN GAME" }
          - { entity: "Personnage" }
          - { label: "STATIC" }
          - { entity: "Classe" }
          - { entity: "Race" }
          - { entity: "Arme" }
          - { entity: "Armure" }

  entities:
    Personnage:
      class: App\Entity\Personnage
      list:
        actions:
          - { name: "edit", icon: "pencil", label: "Modifier" }
          - { name: "delete", icon: "trash", label: "Supprimer" }
      form:
        fields:
          - { type: "tab", label: " Personnage", icon: "user" }
          - { property: "nom" }
          - { property: "race" }
          - { property: "classe" }

          - { type: "tab", label: "Equipement", icon: "newspaper-o" }
          - { property: "arme", label: "Main gauche" }
          - { property: "armure", label: "Main droite" }

    Race:
      class: App\Entity\Race
      list:
        actions:
          - { name: "edit", icon: "pencil", label: "Modifier" }
          - { name: "delete", icon: "trash", label: "Supprimer" }
      form:
        fields:
          - { type: "tab", label: "Race", icon: "user" }
          - { property: "libelle" }
          - { property: "description" }
          - { property: "sante" }
          - { property: "force" }
          - { property: "magie" }
          - { property: "defense" }
    Classe:
      class: App\Entity\Classe
      list:
        actions:
          - { name: "edit", icon: "pencil", label: "Modifier" }
          - { name: "delete", icon: "trash", label: "Supprimer" }
      form:
        fields:
          - { type: "tab", label: "Classe", icon: "user" }
          - { property: "libelle" }
          - { property: "decription" }
          - { property: "savoir" }
          - { property: "physique" }
          - { property: "dexterite" }
          - { property: "sens" }

    Arme:
      class: App\Entity\Arme
      list:
        actions:
          - { name: "edit", icon: "pencil", label: "Modifier" }
          - { name: "delete", icon: "trash", label: "Supprimer" }
      form:
        fields:
          - { type: "tab", label: "Arme", icon: "user" }
          - { property: "libelle" }
          - { property: "description" }
          - { property: "bonus_physique", type: integer }
          - { property: "bonus_savoir", type: integer }
          - { property: "bonus_dexterite", type: integer }
          - { property: "bonus_sens", type: integer }
    Armure:
      class: App\Entity\Armure
      list:
        actions:
          - { name: "edit", icon: "pencil", label: "Modifier" }
          - { name: "delete", icon: "trash", label: "Supprimer" }
      form:
        fields:
          - { type: "tab", label: "Armure", icon: "user" }
          - { property: "libelle" }
          - { property: "description" }
          - { property: "bonus_physique", type: integer }
          - { property: "bonus_savoir", type: integer }
          - { property: "bonus_dexterite", type: integer }
          - { property: "bonus_sens", type: integer }
