easy_admin:
  entities:
    Arme:
      class: App\Entity\Arme
      list:
        actions:
          - { name: "edit", icon: "pencil", label: "Modifier" }
          - { name: "delete", icon: "trash", label: "Supprimer" }
      form:
        fields:
          - { type: "tab", label: "Arme", icon: "user" }
          - { property: "libelle" }
          - { property: "description" }
          - { property: "bonus_physique", type: integer }
          - { property: "bonus_savoir", type: integer }
          - { property: "bonus_dexterite", type: integer }
          - { property: "bonus_sens", type: integer }
    